baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'book'

[params]
  # Book theme parameters
  BookSection = 'docs'
  BookSearch = true
  BookComments = false
